version: '3'
services:
  server:
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file: ./.env
    image: server:server
    command: ["./src/wait-for-it.sh", "postgres:5432", "--", "node", "bin/server"]
    depends_on:
      - postgres
    ports:
    - "2345:8080"
  postgres:
    image: postgres:9.4
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d/
    ports:
    - "5432:5432"
